### ISSUE TITLE
Finding the default printer

### ISSUE THREAD

**Issue by jwoertink** [williamkapke/ipp#13]
Does ipp support finding the current default printer of the machine? I tried using the findPrinters example, but the printer that prints out isn't my default. I have several printers connected to my machine, and I'm able to print to my default from ipp, but it doesn't show up with the mdns example.

**Comment by williamkapke** [comment]
I do not think there is a way to do it. MDNS doesn't have any awareness of users and setting a default printer is a per-user thing. Sry.

**Comment by georgeawg** [comment]
The CUPS server extensions are documented at:

http://www.cups.org/documentation.php/spec-ipp.html

CUPS-Get-Default	1.0	0x4001	Get the default destination.
CUPS-Get-Printers	1.0	0x4002	Get all of the available printers.

See my example on how to get the available printers

[lpstat implemented in JavaScript](https://gist.github.com/georgeawg/2aacd1618986a890ac20)
