### ISSUE TITLE
My printer only supports BJL, BJRaster3 and BSCCe ... I'm lost?

### ISSUE THREAD

**Issue by SunboX** [williamkapke/ipp#16]
Hey,

my printer doesn't seem to support PDF. :sob: 
 My print-server's printer information tells me, it's supported printing languages are BJL, BJRaster3 and BSCCe (Canon iP5000).

Is there any chance to print on it using `ipp.js` & the Bubble Jet Language (superset of the IBM ProPrinter) :question:

**Comment by williamkapke** [comment]
Sorry- I don't know about Canon printers. If you can find something to generate those languages, you can certainly use IPP to send it to the printer. If you figure it out- feel free to post here to help the next person!

**Comment by SunboX** [comment]
Thanks for your feedback! :blush: 

The protocol to be used is called [**BJNP**](http://www.qwhatis.com/what-is-bjnp/)
There's a CUPS implementation here http://sourceforge.net/p/cups-bjnp/code/HEAD/tree/trunk/backend/ but sadly there's no JavaScript nor Node.JS implementation by now.

**Comment by feltraco** [comment]
You can try emscripten (http://emscripten.org) to compile CUPS code to JavaScript.

**Comment by SunboX** [comment]
Yeah, I know. But I'm not that much experienced with Emscripten. Maybe I can compile it, but I really don't know how to build the entry points / bridges for JavaScript / ipp.js into CUPS. :cry:

**Comment by yorkie** [comment]
I did occurred the same problem with HP DeskJet series printer, which only supports `image/urf`, this module is awesome but missing a compatible works, that's the value of CUPS I guess.

@feltraco using emscripten to build CUPS even though looks good and works, but the generated code might be too huge and long time to load, so I think the best solution is to rewrite these converts :)
