### ISSUE TITLE
Missing required attributes

### ISSUE THREAD

**Issue by jimmybaker** [williamkapke/ipp#17]
I'm trying to print to a Canon printer and I'm getting: 
![Image of error]
(http://cl.ly/image/2Z3h3D1y1o1g/Image%202015-06-10%20at%203.38.52%20PM.png)

Any idea what I'm missing? How could I find out?

**Comment by williamkapke** [comment]
Any chance you can post the raw response data (in hex)?

Maybe just add a console.log(buff.toString('hex')) here and run it again: https://github.com/williamkapke/ipp/blob/master/lib/parser.js#L11

**Comment by jimmybaker** [comment]
I just kept playing with the attributes and got it working with this:

```
printDocument: (data, callback) ->
    uri = Settings.documentPrinter.options['printer-uri-supported']
    ippPrinter = ipp.Printer(uri)
    msg = {
      "operation-attributes-tag": {
        "attributes-charset": "utf-8",
        "attributes-natural-language": "en",
        "document-format": "application/pdf",
        "printer-uri": uri
      },
      data: data
    }

    ippPrinter.execute "Print-Job", msg, (err, res) ->
      callback(res)
```

I think it was two things:

1) The printer-uri is needed
2) It didn't like the requesting-user-name or job-name

**Comment by williamkapke** [comment]
Yeah, when you get into Jobs- it is very vendor specific and a pain. I'm glad to hear you got printing though!
