### ISSUE TITLE
IPP OOP interface

### ISSUE THREAD

**Issue by alepee** [williamkapke/ipp#19]
New topic for this (started here: https://github.com/williamkapke/ipp/issues/3#issuecomment-129950161). 

Thanks for the answer @williamkapke. I started to write an interface depending on your module with two main objects `Printer` and `Job`.

You can get the code on http://github.com/alepee/node-ipp-interface. Project name suggestions are welcome.

We could help each other on this. I ran into the RFC, but as you surely already know it, it's not always crystal clear :smile: 

I currently implemented most common operations (more to come):

```
Printer
  |- constructor // get printer attributes and store your `Printer` object into `this._api`
  |- createJob // return a Job object
  |- getJobs // return res['job-attributes-tag']
  |- pause
  |- resume
```

```
Job
  |- constructor // create a job and get its id, uri and state
  |- send // add a new document to it
  |- process // send signal to start printing it
  |- hold
  |- release
  |- restart
  |- cancel
  |- refresh // get latest state of it
```

I think this is a good starting point, but I now deal with notifications/subscriptions and it's not really clear to me. The goal is to be able to dispatch an event on `Job` object when it changes it state.

Any idea?

**Comment by manuelnucci** [comment]
Hi @alepee. Sorry to bother you after a long time since you closed this issue. Do you know if the library is capable of dispatching the events you were talking about? 

I would really like this feature but sadly it requires also to write the type definitions, as I see that were left aside in the [@types/ipp](https://www.npmjs.com/package/@types/ipp) package.

**Comment by alepee** [comment]
Hello @manuelnucci, I don't think so, the `ipp` library only follow the IPP protocol RFC and allow you to serialize and deserialize messages.
