### ISSUE TITLE
Re-open #12 Warnings given for zero-length 0x13 tags

### ISSUE THREAD

**Issue by georgeawg** [williamkapke/ipp#22]
Re-open issue #12 

This line https://github.com/williamkapke/ipp/blob/master/lib/parser.js#L131

**Was:**
```javascript
case tags.novalue:
```

**Should be:**
```javascript
case tags["no-value"]:
```

See output from: [lpstat implemented in JavaScript] (https://gist.github.com/georgeawg/2aacd1618986a890ac20)

**Comment by williamkapke** [comment]
wow- I did see that you posted this. I'm very sry for the incredible delay!

I'll change it to `tags["no-value"]` and push it out.

Thanks for catching this!
