### ISSUE TITLE
Got Error "server-error-version-not-supported"

### ISSUE THREAD

**Issue by AlexZhouAA** [williamkapke/ipp#23]
Try run the following code, 
<pre><code>
var ipp = require('ipp');

var uri = "http://192.168.0.123:631/lp1";
var data = ipp.serialize({
    "operation":"Get-Printer-Attributes",
    "operation-attributes-tag": {
        "attributes-charset": "utf-8",
        "attributes-natural-language": "en",
        "printer-uri": uri
    }
});

ipp.request(uri, data, function(err, res){
    if(err){
        return console.log(err);
    }
    console.log(JSON.stringify(res,null,2));
})

</code></pre>
Got the following error,
<pre><code>
{
  "version": "1.0",
  "statusCode": "server-error-version-not-supported",
  "id": 0,
  "operation-attributes-tag": {
    "attributes-charset": "utf-8",
    "attributes-natural-language": "en-us"
  }
}
</code></pre>
Please help.
Thanks a lot.

**Comment by AlexZhouAA** [comment]
I read issue #15, fixed

**Comment by williamkapke** [comment]
Ah cool. Sorry couldn't respond- I've been at a conference the last few days. Glad you worked it out.

Cheers.

**Comment by AlexZhouAA** [comment]
Thanks a lot, however I got another problem, 
Submitted as issue #24
