### ISSUE TITLE
job-attributes-tag not working

### ISSUE THREAD

**Issue by nathanhleung** [williamkapke/ipp#25]
I'm trying to print double sided using this code:

```js
let msg = {
      "operation-attributes-tag": {
        "requesting-user-name": req.body.name + " via printerService",
        "job-name": req.body.file,
        // "document-format": "application/pdf" <- this doesn't work, but below does.
        "document-format": "application/octet-stream",
      },
      "job-attributes-tag": {
        "copies": "1",
        "sides": "two-sided-long-edge"
      },
      data: data,
      version: "1.1"
};
printer.execute("Print-Job", msg, (err, res) => {
      console.log(err);
      console.log(res);
});
````

However, when I run it I get the following error:
```js
The spec is not clear on how to handle tag 16. Please open a github issue to help find a solution!
The spec is not clear on how to handle tag 16. Please open a github issue to help find a solution!
null
{ version: '1.1',
  statusCode: 'successful-ok-ignored-or-substituted-attributes',
  id: 42831385,
  'operation-attributes-tag': 
   { 'attributes-charset': 'utf-8',
     'attributes-natural-language': 'en' },
  'unsupported-attributes-tag': { copies: undefined, sides: undefined },
  'job-attributes-tag': 
   { 'job-uri': 'ipp://MY-PRINTER:631/ipp/job-79',
     'job-id': 79,
     'job-state': 'processing',
     'job-state-reasons': 'job-printing',
     'job-state-message': 'Printing...',
     'number-of-intervening-jobs': 0 } }

```

Do you know what's causing the problem?

Thanks.
Nathan

**Comment by williamkapke** [comment]
The response is saying that `copies` and `sides` are not supported by the printer you are using. The log messages are there just to alert you that `ipp` doesn't have a way to read the `unsupported` (tag 16) part of the message because the spec doesn't define _how_ to read it. How that helps.

**Comment by michaelrsweet** [comment]
FWIW, the unsupported tag (and all other out of band tags) are defined as 0-length values. The CUPS source can be used to see how to handle different value tags, or please feel free to post questions to the ipp@pwg.org mailing list...

**Comment by nathanhleung** [comment]
Ok, thanks - the printer supports double-sided printing via the system dialog, so I'll have to look into this a little more.

**Comment by realleoman** [comment]
Hi, @nathanhleung  Were you able to solve this issue? I'm facing the same problem here with no luck :-(
