### ISSUE TITLE
CUPS extensions best practices

### ISSUE THREAD

**Issue by danieloneill** [williamkapke/ipp#28]
Hi there, I love the library and have implemented it in a little server side job which handles printing for a client.

I wanted to list the available printers to the client, which means (in my case) issuing a CUPS-Get-Printers to my server.

I've managed to make it work by doing this:

```
    var ipp = require('ipp');
    ipp.enums["operations-supported"]['CUPS-Get-Default'] = 0x4001;
    ipp.enums["operations-supported"]['CUPS-Get-Printers'] = 0x4002;
```
and
```
    printerList: function(uri, conn, packet)
    {
        var msg = {
            "operation": 'CUPS-Get-Printers',
            "operation-attributes-tag": {
                "attributes-charset": "utf-8",
                "attributes-natural-language": "en",
                "printer-uri": uri
            }
        }

        ipp.request(uri, ipp.serialize(msg), function(err, res){
            var response = { 'function':'printerlist', 'module':'cups', 'result':res };
            if( err )
                response['error'] = err;

            conn.transmit(response);
        });
    }
```

Would it be worth adding CUPS extensions to the enums.js, or is there a reason for omitting vendor extensions?  Is there a "better" way to shoehorn such extensions into working with the library?

Cheers!

**Comment by williamkapke** [comment]
I'm glad you're finding it useful. You are approaching it exactly as intended. I made the `enums` and such exposed just for that reason. 👍 

From time-to-time I get asked about adding CUPS specific things to the library... and I do understand the desire- but CUPS is a system that _uses_ IPP and chooses to extend it.. but is not part of the actual spec.

Also, some people are using this on IoT devices where they are concerned about the size of everything, so they appreciate that doesn't take on more than what they need.

I kinda thought someone would have created another module that applied the CUPS extensions (like you have) by now.
