### ISSUE TITLE
Print-URI not supported

### ISSUE THREAD

**Issue by jmorrisIII** [williamkapke/ipp#32]
I can get it to "Print-Job" but when I try to print using a URI I get the error "Print-URI not supported". Any Ideas?
```
        var printer = ipp.Printer("http://10.0.1.156:631/printers/Kyocera_FS-9530DN");
        var msg = {
            "operation-attributes-tag": {
                "requesting-user-name": "William",
                "job-name": "My Test Job",
                "document-format": "application/pdf",
                "document-uri": "http://10.0.1.156:5000/#/extension/reports/DfUny9LY4tUwxYMZ"
            }
        };
        printer.execute("Print-URI", msg, function(err, d){
                if(err){
                    return res.send(err);
                }
            return res.send(d);
        });
```
returns
```
{
  "version": "2.0",
  "statusCode": "server-error-operation-not-supported",
  "id": 33660406,
  "operation-attributes-tag": {
    "attributes-charset": "utf-8",
    "attributes-natural-language": "en-us",
    "status-message": "Print-URI not supported."
  }
}

**Comment by wifiprintguy** [comment]
The Print-URI operation seems to not be supported by the Printer.

If you send a "Get-Printer-Attributes" operation request to the printer, the response should contain the "operations-supported" Printer Description attribute. If Print-URI isn't listed, then the Printer doesn't support it, and you would have to download the file to the Client system and submit it using Print-Job (or ideally Create-Job and Send-Document if the Printer supports those).

**Comment by michaelrsweet** [comment]
The Print-URI operation is optional - consult the operations-supported attribute to determine whether the printer/server actually supports it. (most printers do not, and CUPS does not, for practical and security reasons...)

**Comment by jmorrisIII** [comment]
The printer does not support it .Thanks
