### ISSUE TITLE
MDNS

### ISSUE THREAD

**Issue by mzammit** [williamkapke/ipp#4]
I keep getting this when requiring mdns:

Unexpected result while probing for avahi: [TypeError: argument 3 must be an integer (interfaceIndex)]
**\* WARNING **\* The program 'node' uses the Apple Bonjour compatibility layer of Avahi
**\* WARNING **\* Please fix your application to use the native API of Avahi!
**\* WARNING **\* For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=node

I don't know what is wrong tbh!

**Comment by triblondon** [comment]
FYI, mdns now appears to be more recently updated than mdns2 and only the former worked for me on OS X today.

**Comment by istiti** [comment]
is it normal i  tried to install mdns and mdns2 and same error can't build make or I dont understand what's passing , can someone help me
![image](https://user-images.githubusercontent.com/2789203/35554200-2700144e-059b-11e8-925d-398a41747849.png)

cc @williamkapke  @triblondon

**Comment by aeksco** [comment]
@istiti Just hit the same problem - looks like I was missing the `libavahi-compat-libdnssd-dev` package. 

Run:
```
sudo apt-get install libavahi-compat-libdnssd-dev
```
Then try running `npm install` again. Good luck!

[Source - mdns README.md](https://github.com/agnat/node_mdns#installation)
