### ISSUE TITLE
Unknown attribute: media-source

### ISSUE THREAD

**Issue by WillCHansen** [williamkapke/ipp#41]
I'm trying to print from a specific tray but I'm unable to set the "media-source" attribute.

    var printer = ipp.Printer(uri);

    var msg = {
        "operation-attributes-tag": {
            "attributes-charset": "utf-8",
            "attributes-natural-language": "en",
            "printer-uri": uri,
            "document-format": "application/pdf"
        },
        "job-attributes-tag": {
            "media-source": "tray-2",
            "copies": "2"
      },
        data: Buffer.concat(buffers)
    }

    printer.execute("Print-Job", msg, function(err, res){
        console.log(JSON.stringify(res,null,2));
    })

returns

U:\pdfparser\node_modules\ipp\lib\serializer.js:64
                if(!groupName) throw "Unknown attribute: " + name;
                               ^
Unknown attribute: media-source

The printer seems to have "media-source" as an attribute.

`"media-source-supported": [
      "auto",
      "tray-1",
      "tray-2",
      "tray-3",
      "tray-4",
      "tray-5"
    ],`

**Comment by wifiprintguy** [comment]
"media-source" is a member attribute (child) of "media-col". So in your job creation operation (Print-Job or Create-Job) you would have to encapsulate your "media-source" attribute within a "media-col" collection, something sort of like this:

var msg = {
    "operation-attributes-tag": {
        "attributes-charset": "utf-8",
        "attributes-natural-language": "en",
        "printer-uri": uri,
        "document-format": "application/pdf"
    },
    "job-attributes-tag": {
       "media-col": {
           "media-source": "tray-2"
        },
        "copies": "2"
  },
    data: Buffer.concat(buffers)
}

**Comment by WillCHansen** [comment]
I appreciate the information!

When I run the code I get this

{
  "version": "2.0",
  "statusCode": "successful-ok-ignored-or-substituted-attributes",
  "id": 98793048,
  "operation-attributes-tag": {
    "attributes-charset": "utf-8",
    "attributes-natural-language": "en"
  },
  "unsupported-attributes-tag": {
    "unknown-attribute-name": [
      null,
      null
    ]
  },
  "job-attributes-tag": {
    "job-uri": "ipp://10.1.205.71/14706",
    "job-id": 14706,
    "job-state": "pending",
    "job-state-reasons": "job-incoming",
    "number-of-intervening-jobs": 4
  }
}

I've read through the documentation and the printer does have "media-col-default" and "media-col-ready" attributes so I'm unsure why they're coming back as unsupported.

**Comment by wifiprintguy** [comment]
Hard to know what is going on since the output says:

    "unsupported-attributes-tag": {
        "unknown-attribute-name": [
            null,
            null
       ]
    },

You might try prototyping your IPP operations using the PWG's "ipptool" and a .test file as a separate IPP client implementation, to confirm that your IPP operation attributes, etc. are correctly formed. You can get that from the PWG's "ippsample" Github project (https://github.com/istopwg/ippsample) or it is part of some CUPS distributions as well.

**Comment by WillCHansen** [comment]
Alright I'll look into that. Thank you for your time.

**Comment by WillCHansen** [comment]
I believe the "media-col" collection is not properly forming with "ipp.serialize".

Please see my example and let me know if any more info is needed. I didn't include the data from the entire msg, just the collection.

`var msg = {
    "operation-attributes-tag": {
        "attributes-charset": "utf-8",
        "attributes-natural-language": "en",
        "printer-uri": uri,
        "document-format": "application/pdf"
    },
    "job-attributes-tag": {
       "media-col": {
           "media-source": "tray-2"
        },
        "copies": "2"
  }
}`

34 begin collection

0009 length

6d65 6469 612d 636f 6c media-col

00 004a collection member

0000 00 missing length? 

0c6d65 6469 612d 736f 7572 6365 media-source

4a00 00 collection member

0006 length

74 7261 792d 32 tray-2

37 end collection

**Comment by WillCHansen** [comment]
I'm going to open a new issue detailing the issue for better visibility.
