### ISSUE TITLE
HP PageWide Pro: Job Name and User-Name

### ISSUE THREAD

**Issue by mcdado** [williamkapke/ipp#44]
We have two HP PageWide Pro printers, 477w and 452dw models.

I am successful at printing jobs, the problem I found is that from the internal web page of the printers we cannot set the Job Names. They appear as follows:

<img width="729" alt="screen shot 2017-08-10 at 11 14 18" src="https://user-images.githubusercontent.com/898057/29163885-1b523bc8-7dbe-11e7-895f-215736058878.png">

You can see how the IPP jobs are indicated with User "Guest" and Job Name "Print".
Here is a snippet of the code I put together using this package:

```node
const printer = ipp.Printer(`http://${hostname}:631/ipp/printer`);
let inputFile = 'whatever.pdf'; // passed in argv, omitted here

[...]

fs.readFile(inputFile, (readErr, pdfData) => {
  if (readErr) {
    throw readErr;
  }

  const payload = {
    'operation-attributes-tag': {
      'requesting-user-name': 'Bumblebee',
      'job-name': path.basename(inputFile),
      'document-format': 'application/pdf',
    },
    data: pdfData,
  };

  const runPrint = () => {
    printer.execute('Print-Job', payload, (executeErr, res) => {
      if (executeErr) {
        const fileName = path.basename(inputFile);
        slack.sendNotification({
          channel: '#prepress',
          text: `Printing the file *${fileName}* has failed. @here`,
          link_names: true,
        })
        .then(() => {
          throw executeErr;
        });
      }

      if (res.statusCode === 'server-error-busy') {
        setTimeout(runPrint, 1000);
      }
    });
  };

  runPrint();
});
```

Do you have any experience in successfully working with HP printers? I tried googling but I could find their IPP internals spec, maybe the use some custom fields for attributes?

**Comment by williamkapke** [comment]
I have an HP next to me- but it doesn't have a status page like yours. 🤔 

Run this and see what the output is:
```js
const ipp = require('ipp');
const printer = ipp.Printer(`http://${hostname}:631/ipp/printer`);

var msg = {
  "operation-attributes-tag": {
   //use these to view completed jobs...
//	"limit": 10,
    "which-jobs": "completed",
    "requested-attributes": [
      "job-id",
      "job-uri",
      "job-state",
      "job-state-reasons",
      "job-name",
      "job-originating-user-name",
      "job-media-sheets-completed"
    ]
  }
}

printer.execute("Get-Jobs", msg, function(err, res){
  if (err) return console.log(err);
  console.log(res['job-attributes-tag']);
});
```

All attributes that you're allowed to use __*should*__ be returned from a `Get-Printer-Attributes` request. Scan through that response and look for fields to try out.

For the `User` column, do those printers support authentication? Maybe they're connected to a domain? (kinda looks like it). If so, I'd guess that column isn't an IPP thing- just the endpoint's authentication. You could try to add a username and password to the url.

**Comment by mcdado** [comment]
Thank you for your time and effort!

In the end we figured out a way to not having to resort to IPP and we managed to automatically control Acrobat (ugh) and print through it, which is somewhat more reliable than my put-together scripts, and also the job report is filled properly… but for the sake of completeness and respect I'll paste the results of the command you suggested:
```
[ { 'job-uri': 'ipp://hpdeadbeef.local/ipp/print/job-0061',
    'job-id': 61,
    'job-name': 'en-us\u001e_03GCI_SL_17P2336p01.pdf',
    'job-originating-user-name': 'en-us\u001eSwitch',
    'job-state': 'completed',
    'job-state-reasons': 'none',
    'job-media-sheets-completed': 1,
    'job-mandatory-attributes': undefined },
  { 'job-uri': 'ipp://hpdeadbeef.local/ipp/print/job-0060',
    'job-id': 60,
    'job-name': 'en-us\u001e_03GCA_SL_17P2336p02.pdf',
    'job-originating-user-name': 'en-us\u001eSwitch',
    'job-state': 'completed',
    'job-state-reasons': 'none',
    'job-media-sheets-completed': 1,
    'job-mandatory-attributes': undefined },
  { 'job-uri': 'ipp://hpdeadbeef.local/ipp/print/job-0059',
    'job-id': 59,
    'job-name': 'en-us\u001epaypal-letter-of-authorization.pdf',
    'job-originating-user-name': 'en-us\u001eBumblebee',
    'job-state': 'completed',
    'job-state-reasons': 'none',
    'job-media-sheets-completed': 1,
    'job-mandatory-attributes': undefined },
  { 'job-uri': 'ipp://hpdeadbeef.local/ipp/print/job-0058',
    'job-id': 58,
    'job-name': 'en-us\u001epaypal-letter-of-authorization.pdf',
    'job-originating-user-name': 'en-us\u001eBumblebee',
    'job-state': 'completed',
    'job-state-reasons': 'none',
    'job-media-sheets-completed': 1,
    'job-mandatory-attributes': undefined },
  { 'job-uri': 'ipp://hpdeadbeef.local/ipp/print/job-0057',
    'job-id': 57,
    'job-name': 'en-us\u001epaypal-letter-of-authorization.pdf',
    'job-originating-user-name': 'en-us\u001eBumblebee',
    'job-state': 'completed',
    'job-state-reasons': 'none',
    'job-media-sheets-completed': 1,
    'job-mandatory-attributes': undefined } ]
```
(I changed the hostname to a very random hex address).

You'll see that the "job-originating-user-name" changes, I'm pretty sure it's because I did change it between tests… I looked at the list on the web interface (in this case the 477dw model, the 452dw doesn't have it) and all these jobs are Guest/Print. I'm guessing the printer software doesn't pull out such info from the IPP jobs.

Also, I tried enabling Access Control and put username:password in the connection string, it never worked. Yes in the network there is a domain, but I don't think I made the printer join it.
