### ISSUE TITLE
Printer printing blank pages

### ISSUE THREAD

**Issue by PepperedJerky** [williamkapke/ipp#71]
Hello, I've messed around a lot with this library trying to get my printer to print anything at all, and I've scoured the response attributes to try and get more info on my printer.

First some possibly useful info:

Printer: **Brother HL-L2340DW**
Printer Type: **Monochrome Laser Printer**
Document formats supported: **application/octet-stream, image/urf, image/pwg-raster**
Get-Printer-Attributes response: https://pastebin.com/8G9pdfpP

For all examples, I have tried using versions 1.0 and 2.0.

Here's a few examples I've tried to get working with my printer but was for whatever reason unsuccessful, and maybe someone can give me some ideas on what the problem might be.

Example 1:

```
let ipp = require("ipp");
let PDFDocument = require("pdfkit");

let doc = new PDFDocument;
doc.text("Hello World");

let buffers = [];
doc.on('data', buffers.push.bind(buffers));
doc.on('end', function () {

    console.log(Buffer.concat(buffers));

    let printer = ipp.Printer("ipp://192.168.2.202:631/ipp/print", {version:'1.0'});
    let file = {
        "operation-attributes-tag":{
        "requesting-user-name": "User",
        "job-name": "Print Job",
        "document-format": "application/octet-stream"
        },
        data: Buffer.concat(buffers)
    };

    printer.execute("Print-Job", file, function (err, res) {
        console.dir(res);
    });
});
 doc.end();
```

Printer response for example 1:

```
{ version: '1.0',
  statusCode: 'successful-ok',
  id: 12219796,
  'operation-attributes-tag':
   { 'attributes-charset': 'utf-8',
     'attributes-natural-language': 'en-us' },
  'job-attributes-tag':
   { 'job-uri': 'ipp://192.168.2.202:631/ipp/print/job-64',
     'job-id': 64,
     'job-state': 'processing',
     'job-state-reasons': [ 'job-incoming', 'job-printing' ] } }
```

What happens when I use this code is it prints 2 blank pages, or just 1 if I change the doc font size to a larger size like 25 using `doc.fontSize(25)`.

Example 2:

```
let ipp = require("ipp");
let printer = ipp.Printer("ipp://192.168.2.202:631/ipp/print", {version:'1.0'});

let data = {
    "operation-attributes-tag": {
        "requesting-user-name": "User",
        "job-name": "Print Job",
        "document-format": "application/octet-stream"
    },
    data: Buffer.from("Test", 'utf8')
}

printer.execute("Print-Job", data, function(err, res){
    console.log(err);
    console.log(res);
});
```

Printer response for example 2: Nothing...

When using this code, the printer seems to freeze or something, basically if I try to send another print job request, it just responds with `statusCode: 'server-error-busy'` and I have to power cycle my printer to get it working again.

Update for example 2: I noticed if the buffer contains less than like 8 characters (Not sure exactly how many, but it's around that), it freezes like this, otherwise, it just responds with the same response from example 1 but prints nothing (not blank pages, just nothing happens).

So, sorry for this kind of crappily formed question, but does anyone have any ideas? Thanks :)

**Comment by thenewguy** [comment]
If you need to print to that printer specifically, and you're confident
you're sending the request correctly, I'd confirm that you can print
through cups to the printer. Then to cups via this lib. Might have to proxy
the cups printer for cors headers unless you can adjust cups to send them
(last I checked you can't).

**Comment by milena357** [comment]
Hi, 

Were you able to resolve this?

**Comment by guy-bartkus** [comment]
> Hi,
> 
> Were you able to resolve this?

Nope. I haven't tried with other printers either but I might, it may have just been that printer I was using.

**Comment by milena357** [comment]
I have been having this issue with a few different Brother printer models. They are just not printing anything. HP printers work fine.

**Comment by williamkapke** [comment]
Are you sure the Brother printer supports PDF printing? I believe I recall having blank pages when sending a format a printer doesn't understand.
