### ISSUE TITLE
characters that have a code upper than 127 are not printed correctly

### ISSUE THREAD

**Issue by atiertant** [williamkapke/ipp#91]
using this code:

```
var ipp = require('ipp');
var PRINTER_URL = "http://x.x.x.x:631/ipp/printer";
var printer = ipp.Printer(PRINTER_URL, {language: 'fr'});
var msg = {
  "operation-attributes-tag": {
    "requesting-user-name": "Atlbusiness",
    "job-name": 'test',
    'attributes-natural-language': 'fr',
    "document-format": "application/octet-stream"
  },
  data: Buffer.from('abcd é')
};

printer.execute("Print-Job", msg, function(err, res){
  if (err) {
    console.log(err);
  }
  console.log(JSON.stringify(res));
});
```

the printer print correctly "abcd" but the "é" is not printed correctly, there is on other character instead.
this is the same for all characters that have a code upper than 127.

the result logged is:
`{"version":"2.0","statusCode":"successful-ok","id":6110892,"operation-attributes-tag":{"attributes-charset":"utf-8","attributes-natural-language":"en"},"job-attributes-tag":{"job-uri":"ipp://NPIB4564E.local/ipp/print/0802","job-id":802,"job-state":"pending","job-state-reasons":"none"}}`

i tryed add/remove language option and attributes-natural-language but nothing help

**Comment by atiertant** [comment]
this was a bug in my pclkit lib, now fixed

**Comment by hx8321** [comment]
When I used the IPP library, I also encountered this print task being suspended. How did you deal with it?
